In [1]:
import numpy as np
import matplotlib.pyplot as plt
import json

In [5]:

with open("ckpts/ppo_rm_wikiplots_llama7B_true2_false-3_kl0pt5/checkpoint_030000/hf_model/factscores_eval.json", "r") as f:
    factscores = json.load(f)


num_true_all = []
num_total_all = []
frac_correct_facts = []
num_none_decisions = 0
for i in range(len(factscores["decisions"])):
    decison = factscores["decisions"][i]
    if decison == None:
        num_total_all.append(0)
        num_true_all.append(0)
        frac_correct_facts.append(0)
        num_none_decisions += 1

    else:
        num_total_all.append(len(decison))
        num_true_all.append(np.sum([fact["is_supported"] for fact in decison]))
        frac_correct_facts.append(np.sum([fact["is_supported"] for fact in decison])/len(decison))
num_total_all = np.array(num_total_all)
num_true_all = np.array(num_true_all)
frac_correct_facts = np.array(frac_correct_facts)
num_false_all = num_total_all - num_true_all

In [6]:

def get_bin_average(x_axis, y_axis, bins):
    x_axis = np.array(x_axis)
    y_axis = np.array(y_axis)
    bin_avgs = []
    for i in range(len(bins)-1):
        idxs = np.where((x_axis >= bins[i]) & (x_axis < bins[i+1]))[0]
        bin_avgs.append(np.mean(y_axis[idxs]))
    return np.array(bin_avgs)

In [7]:
num_pretrain_entities = np.load("num_pretrain_entities/wikiplots_test_points.npy", )

num_entities_bins = [0, 200, 400, 600, 800, 1000, np.inf]


In [14]:

with open("ckpts/ppo_rm_wikiplots_llama7B_true2_false-3_kl0pt5/checkpoint_030000/hf_model/factscores_eval.json", "r") as f:
# with open("ckpts/sft_wikiplots_common_llama7B/checkpoint_15000/hf_model/factscores_test_medium.json", "r") as f:
    factscores = json.load(f)


num_true_all = []
num_total_all = []
frac_correct_facts = []
num_none_decisions = 0
for i in range(len(factscores["decisions"])):
    decison = factscores["decisions"][i]
    if decison == None:
        num_total_all.append(0)
        num_true_all.append(0)
        frac_correct_facts.append(0)
        num_none_decisions += 1

    else:
        num_total_all.append(len(decison))
        num_true_all.append(np.sum([fact["is_supported"] for fact in decison]))
        frac_correct_facts.append(np.sum([fact["is_supported"] for fact in decison])/len(decison))
num_total_all = np.array(num_total_all)
num_true_all = np.array(num_true_all)
frac_correct_facts = np.array(frac_correct_facts)
num_false_all = num_total_all - num_true_all

In [12]:
get_bin_average(num_pretrain_entities, num_true_all, num_entities_bins)

array([1.82635659, 2.01574803, 2.03529412, 2.21367521, 2.1443299 ,
       2.74453552])

In [13]:
get_bin_average(num_pretrain_entities, num_false_all, num_entities_bins)

array([2.70387597, 2.81102362, 2.49411765, 2.34188034, 2.50515464,
       1.93169399])

In [15]:
get_bin_average(num_pretrain_entities, num_true_all, num_entities_bins)

array([2.89767442, 3.10629921, 2.97058824, 3.41880342, 3.18556701,
       3.8920765 ])

In [16]:
get_bin_average(num_pretrain_entities, num_false_all, num_entities_bins)

array([0.63410853, 0.59448819, 0.6       , 0.5042735 , 0.67010309,
       0.49726776])

In [4]:
plt.plot([_ for _ in range(len(num_true_all_binned))], num_true_all_binned, 'o-')
# plt.fill_between([0, 1, 2, 3], num_true_all_binned - num_true_all_binned_std, num_true_all_binned + num_true_all_binned_std, alpha=0.5)
plt.plot([_ for _ in range(len(num_true_all_binned))], num_true_all_binned2, 'o-')
# plt.fill_between([0, 1, 2, 3], num_true_all_binned2 - num_true_all_binned_std2, num_true_all_binned2 + num_true_all_binned_std2, alpha=0.5)

plt.plot([_ for _ in range(len(num_true_all_binned))], num_true_all_binned3, 'o-')

plt.ylim(0, 4)

{'score': 0.8030818417713017,
 'respond_ratio': 0.9987486965589155,
 'decisions': [[{'atom': 'Kevin McCallister is an eight-year-old boy.',
    'is_supported': True},
   {'atom': "Kevin McCallister's family goes on Christmas vacation.",
    'is_supported': True},
   {'atom': "Kevin McCallister's family goes on Christmas vacation to Paris, France.",
    'is_supported': True},
   {'atom': 'Kevin McCallister is accidentally left behind.',
    'is_supported': True},
   {'atom': "Kevin McCallister's family leaves for Paris, France without him.",
    'is_supported': True}],
  [{'atom': 'The Terror is a TV series.', 'is_supported': False},
   {'atom': 'The Terror is a fictionalized account.', 'is_supported': False},
   {'atom': "The Terror is based on the lost expedition of Sir John Franklin's HMS Erebus and HMS Terror.",
    'is_supported': False},
   {'atom': 'The lost expedition became trapped in the Arctic ice.',
    'is_supported': False},
   {'atom': 'The lost expedition perished in 184