In [1]:
import numpy as np

In [2]:
model1_1 = "ckpts/ppo_lama_llama7B_2_commit14_lr5e-4/checkpoint_01000/hf_model"
model2_1 = "ckpts/ppo_lama_llama7B_2_commit14_lr5e-5/checkpoint_01000/hf_model"

model1_2 = "ckpts/ppo_lama_llama7B_2_commit14_lr5e-4/checkpoint_10000/hf_model"
model2_2 = "ckpts/ppo_lama_llama7B_2_commit14_lr5e-5/checkpoint_10000/hf_model"

In [4]:
model1_1_logits = np.load(model1_1 + "/answer_logits.npy")
model2_1_logits = np.load(model2_1 + "/answer_logits.npy")

model1_2_logits = np.load(model1_2 + "/answer_logits.npy")
model2_2_logits = np.load(model2_2 + "/answer_logits.npy")

In [5]:
model1_1_logits == model2_1_logits

array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  Tr

In [6]:
model1_1_logits == model1_2_logits

array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  Tr

In [8]:
(model1_2_logits == model1_2_logits).sum()/model1_2_logits.size

1.0

In [9]:
model1_2_logits.size

35200000

In [10]:
import torch

In [21]:
torch.load(model1_2 + "/pytorch_model.bin", map_location=torch.device('cpu'))

OrderedDict([('v_head.0.weight',
              tensor([[ 0.1031,  0.0032,  0.0470,  ...,  0.0687,  0.0043, -0.0643],
                      [ 0.0114, -0.0008,  0.0028,  ...,  0.0143, -0.0224,  0.0138],
                      [ 0.0048, -0.0192,  0.0097,  ..., -0.0162, -0.0159, -0.0051],
                      ...,
                      [ 0.0162, -0.0176,  0.0025,  ..., -0.0087, -0.0186,  0.0088],
                      [-0.0220,  0.0036, -0.0020,  ..., -0.0025, -0.0397, -0.0285],
                      [ 0.0182, -0.0203,  0.0029,  ...,  0.0067,  0.0167,  0.0064]])),
             ('v_head.0.bias',
              tensor([-0.0653, -0.0167, -0.0043,  ..., -0.0153, -0.0422, -0.0135])),
             ('v_head.2.weight',
              tensor([[-0.0022,  0.0020, -0.0017,  ..., -0.0005, -0.0147, -0.0020]])),
             ('v_head.2.bias', tensor([0.0338]))])

In [20]:
torch.load(model2_2 + "/pytorch_model.bin", map_location=torch.device('cpu'))

OrderedDict([('v_head.0.weight',
              tensor([[ 0.0108,  0.0019, -0.0073,  ...,  0.0009, -0.0061, -0.0022],
                      [-0.0116,  0.0056, -0.0031,  ...,  0.0032, -0.0146, -0.0095],
                      [-0.0023,  0.0082,  0.0165,  ...,  0.0042, -0.0188, -0.0052],
                      ...,
                      [ 0.0181, -0.0172,  0.0047,  ..., -0.0101, -0.0080,  0.0046],
                      [ 0.0068,  0.0179, -0.0147,  ...,  0.0059, -0.0032,  0.0060],
                      [ 0.0104, -0.0165, -0.0024,  ...,  0.0096,  0.0193,  0.0089]])),
             ('v_head.0.bias',
              tensor([-0.0174,  0.0097,  0.0045,  ..., -0.0152, -0.0088, -0.0103])),
             ('v_head.2.weight',
              tensor([[-0.0101, -0.0066, -0.0187,  ..., -0.0059,  0.0005, -0.0084]])),
             ('v_head.2.bias', tensor([-0.0065]))])

In [15]:
torch.load(model1_1 + "/adapter_model.bin", map_location=torch.device('cpu'))

{'base_model.model.model.layers.0.self_attn.q_proj.lora_A.weight': tensor([[-0.0081, -0.0035, -0.0131,  ...,  0.0090,  0.0041, -0.0085],
         [-0.0091,  0.0135,  0.0104,  ..., -0.0096, -0.0009,  0.0051],
         [-0.0192, -0.0098, -0.0103,  ...,  0.0047, -0.0064,  0.0002],
         ...,
         [-0.0173,  0.0114, -0.0031,  ..., -0.0088,  0.0066, -0.0059],
         [ 0.0016, -0.0030, -0.0030,  ..., -0.0174,  0.0007, -0.0112],
         [ 0.0161, -0.0031,  0.0111,  ..., -0.0091,  0.0042,  0.0078]]),
 'base_model.model.model.layers.0.self_attn.q_proj.lora_B.weight': tensor([[-2.0199e-03, -1.3857e-03,  1.4893e-03,  ...,  3.1417e-03,
           2.7804e-04, -1.2261e-03],
         [ 9.7591e-04,  4.0128e-04, -1.0598e-03,  ..., -1.8612e-03,
           5.0496e-06,  6.0688e-04],
         [ 4.7281e-05, -6.5265e-04,  1.1192e-03,  ...,  1.3775e-03,
          -1.3784e-03, -3.1957e-04],
         ...,
         [-1.2405e-03, -4.5773e-05, -1.9489e-03,  ..., -1.4280e-03,
           2.4085e-03, -1.011

In [16]:
torch.load("ckpts/ppo_lama_llama7B_2_commit14_lr5e-4/checkpoint_01000/adapter_model.bin" ,  map_location=torch.device('cpu'))

{'base_model.model.model.layers.0.self_attn.q_proj.lora_A.weight': tensor([[-0.0081, -0.0035, -0.0131,  ...,  0.0090,  0.0041, -0.0085],
         [-0.0091,  0.0135,  0.0104,  ..., -0.0096, -0.0009,  0.0051],
         [-0.0192, -0.0098, -0.0103,  ...,  0.0047, -0.0064,  0.0002],
         ...,
         [-0.0173,  0.0114, -0.0031,  ..., -0.0088,  0.0066, -0.0059],
         [ 0.0016, -0.0030, -0.0030,  ..., -0.0174,  0.0007, -0.0112],
         [ 0.0161, -0.0031,  0.0111,  ..., -0.0091,  0.0042,  0.0078]]),
 'base_model.model.model.layers.0.self_attn.q_proj.lora_B.weight': tensor([[-2.0199e-03, -1.3857e-03,  1.4893e-03,  ...,  3.1417e-03,
           2.7804e-04, -1.2261e-03],
         [ 9.7591e-04,  4.0128e-04, -1.0598e-03,  ..., -1.8612e-03,
           5.0496e-06,  6.0688e-04],
         [ 4.7281e-05, -6.5265e-04,  1.1192e-03,  ...,  1.3775e-03,
          -1.3784e-03, -3.1957e-04],
         ...,
         [-1.2405e-03, -4.5773e-05, -1.9489e-03,  ..., -1.4280e-03,
           2.4085e-03, -1.011

In [17]:
torch.load("ckpts/sft_lama_llama7B_2_commit_idk_lr1e-5/checkpoint_3000/hf_model/adapter_model.bin" ,  map_location=torch.device('cpu'))

{'base_model.model.model.layers.0.self_attn.q_proj.lora_A.weight': tensor([[-0.0081, -0.0035, -0.0131,  ...,  0.0090,  0.0041, -0.0085],
         [-0.0091,  0.0135,  0.0104,  ..., -0.0096, -0.0009,  0.0051],
         [-0.0192, -0.0098, -0.0103,  ...,  0.0047, -0.0064,  0.0002],
         ...,
         [-0.0173,  0.0114, -0.0031,  ..., -0.0088,  0.0066, -0.0059],
         [ 0.0016, -0.0030, -0.0030,  ..., -0.0174,  0.0007, -0.0112],
         [ 0.0161, -0.0031,  0.0111,  ..., -0.0091,  0.0042,  0.0078]]),
 'base_model.model.model.layers.0.self_attn.q_proj.lora_B.weight': tensor([[-2.0199e-03, -1.3857e-03,  1.4893e-03,  ...,  3.1417e-03,
           2.7804e-04, -1.2261e-03],
         [ 9.7591e-04,  4.0128e-04, -1.0598e-03,  ..., -1.8612e-03,
           5.0496e-06,  6.0688e-04],
         [ 4.7281e-05, -6.5265e-04,  1.1192e-03,  ...,  1.3775e-03,
          -1.3784e-03, -3.1957e-04],
         ...,
         [-1.2405e-03, -4.5773e-05, -1.9489e-03,  ..., -1.4280e-03,
           2.4085e-03, -1.011